// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://liyuibfvmwmiriyroaqg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxpeXVpYmZ2bXdtaXJpeXJvYXFnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNTY4OTEsImV4cCI6MjA2NzczMjg5MX0.LExDJhxleQLFK2d-KVtF0ShZGsAlWVRAS7GkvK2f7wg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});